import { Fragment, memo } from "react";

//react bootstrap
import { Container } from "react-bootstrap";

// components
import BreadcrumbWidget from "../../components/BreadcrumbWidget";

// the hook
import { useTranslation } from "react-i18next";

const PrivacyPolicy = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <BreadcrumbWidget title={t("header.privacy_policy")} />
      <div className="section-padding">
        <Container>
          <div className="title-box">
            <h4 className="mb-4">1. Introduction</h4>
            <p className="mb-0">Welcome to SL Flicks.</p>
            <br/>
            <p className="mb-0">SL Flicks (“us”, “we”, or “our”) operates slflicks.com (hereinafter referred to as
              “Service”). </p><br/>
            <p className="mb-0">Our Privacy Policy governs your visit to slflicks.com, and explains how we collect,
              safeguard
              and disclose information that results from your use of our Service. </p><br/>
            <p className="mb-0">We use your data to provide and improve Service. By using Service, you agree to the
              collection
              and use of information in accordance with this policy. Unless otherwise defined in this Privacy
              Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and
              Conditions. </p><br/>
            <p className="mb-0">Our Terms and Conditions (“Terms”) govern all use of our Service and together with the
              Privacy
              Policy constitutes your agreement with us (“agreement”). </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">2. Definitions </h4>
            <p className="">SERVICE means the slflicks.com website or “SL Flicks” Mobile application operated by Susila
              Holdings Private Limited.</p><br/>
            <p className="">PERSONAL DATA means data about a living individual who can be identified from those data
              (or from those and other information either in our possession or likely to come into our
              possession).</p><br/>
            <p className="">USAGE DATA is data collected automatically either generated by the use of Service or from
              Service infrastructure itself (for example, the duration of a page visit). </p><br/>
            <p className="">COOKIES are small files stored on your device (Television, Computer or mobile device). </p>
            <br/>
            <p className="mb-0">DATA CONTROLLER means a natural or legal person who (either alone or jointly or in
              common
              with other persons) determines the purposes for which and the manner in which any personal
              data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data
              Controller of your data. </p><br/>
            <p className="mb-0">DATA PROCESSORS (OR SERVICE PROVIDERS) mean any natural or legal person who
              processes the data on behalf of the Data Controller. We may use the services of various Service
              Providers in order to process your data more effectively. </p><br/>
            <p className="mb-0">DATA SUBJECT is any living individual who is the subject of Personal Data. </p><br/>
            <p className="mb-0">THE USER is the individual using our Service. The User corresponds to the Data Subject,
              who
              is the subject of Personal Data. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">3. Information Collection and Use </h4>
            <p className="mb-0">We collect several different types of information for various purposes to provide and
              improve our
              Service to you. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">4.Types of Data Collected </h4>
            <h5 className="mb-4">4.1 Personal Data </h5>
            <p className="mb-0">While using our Service, we may ask you to provide us with certain personally
              identifiable
              information that can be used to contact or identify you (“Personal Data”). Personally
              identifiable information may include, but is not limited to: </p><br/>
            <p className="mb-0">4.1.1. Email address </p>
            <p className="mb-0">4.1.2. First name and last name </p>
            <p className="mb-0">4.1.3. Phone number</p>
            <p className="mb-0">4.1.4. Address, Country, State, Province, ZIP/Postal code, City</p>
            <p className="mb-0">4.1.5. Cookies and Usage Data</p><br/>
            <p className="mb-0">We may use your Personal Data to contact you with newsletters, marketing or promotional
              materials and other information that may be of interest to you pertaining to our app (SL Flicks).
              You may opt out of receiving any, or all, of these communications from us by following the
              unsubscribe link. </p><br/>
            <h5 className="mb-4">Usage Data </h5>
            <h5 className="mb-4">4.2 Information We Collect </h5>
            <p className="mb-0">We may collect the following types of personal information from you: </p>
            <p className="mb-0">4.2.1. Information you provide to us directly: When you use the App, you may
              provide us with personal information such as your name, email address,
              phone number, and other information you choose to provide. </p><br/>
            <p className="mb-0">4.2.2. Information we collect automatically: When you use the App, we may
              automatically collect certain information about you, including your device
              information, IP address, browser type, and other usage information.
              (“Usage Data”) the time and date of your visit, the time spent on those
              pages, unique device identifiers and other diagnostic data. </p>
            <p className="mb-0">This Usage Data may include information such as your computer’s Internet Protocol
              address
              (e.g. IP address), browser type, browser version, the pages of our Service that you visit, </p>
            <p className="mb-0">4.2.3. Information we collect from third-party sources: We may receive personal
              information about you from third-party sources such as social media
              platforms. </p><br/>
            <h5 className="mb-4">4.3 Tracking Cookies Data </h5>
            <p className="mb-0">We use cookies and similar tracking technologies to track the activity on our Service
              and we
              hold certain information. </p><br/>
            <p className="mb-0">Cookies are files with a small amount of data which may include an anonymous unique
              identifier. Cookies are sent to your browser from a website and stored on your device. Other
              tracking technologies are also used such as beacons, tags and scripts to collect and track
              information and to improve and analyze our Service.</p><br/>
            <p className="mb-0">You can instruct your browser to refuse all cookies or to indicate when a cookie is
              being sent.
              However, if you do not accept cookies, you may not be able to use some portions of our
              Service. </p><br/>
            <p className="mb-0">Examples of Cookies we use: </p><br/>
            <p className="mb-0">4.3.1. Session Cookies: We use Session Cookies to operate our Service. </p>
            <p className="mb-0">4.3.2. Preference Cookies: We use Preference Cookies to remember your
              preferences and various settings. </p>
            <p className="mb-0">4.3.3. Security Cookies: We use Security Cookies for security purposes. </p>
            <p className="mb-0">4.3.4. Advertising Cookies: Advertising Cookies are used to serve you with
              advertisements that may be relevant to you and your interests. </p><br/>
            <h5 className="mb-4">4.5 Other Data </h5><br/>
            <p>While using our Service, we may also collect the following information: sex, age, date of birth,
              place of birth, passport details, citizenship, registration at place of residence and actual address,
              telephone number (work, mobile), details of documents on education, qualification, professional
              training, employment agreements, NDA agreements, information on bonuses and
              compensation, information on marital status, family members, social security (or other taxpayer
              identification) number, office location and other data.</p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              5. Use of Data/Information
            </h4><br/>
            <p className="mb-0">SL Flicks uses the collected data for various purposes: </p><br/>
            <p className="mb-0">5.1 To provide and improve the App: We use your personal information to provide and
              improve the App, including to personalize your experience and to analyze how you
              use the App. </p><br/>
            <p className="mb-0">5.2 To communicate with you: We may use your personal information to communicate
              with you about the App, including to provide customer support and to notify you
              about changes to our Service; </p><br/>
            <p className="mb-0">5.3 to allow you to participate in interactive features of our Service when you choose
              to
              do so; </p><br/>
            <p className="mb-0">5.4 to provide customer support; </p><br/>
            <p className="mb-0">5.5 To send you marketing and promotional communications: We may use your
              personal information to send you marketing and promotional communications about
              the App or our services.</p><br/>
            <p className="mb-0">5.6 to gather analysis or valuable information so that we can improve our Service; </p>
            <br/>
            <p className="mb-0">5.7 to monitor the usage of our Service; </p><br/>
            <p className="mb-0">5.8 to detect, prevent and address technical issues; </p><br/>
            <p className="mb-0">5.9 to fulfil any other purpose for which you provide it; </p><br/>
            <p className="mb-0">5.10 to carry out our obligations and enforce our rights arising from any contracts
              entered
              into between you and us, including for billing and collection;</p><br/>
            <p className="mb-0">5.11 To comply with legal obligations: We may use your personal information to comply
              with legal obligations, including to respond to lawful requests from public authorities.</p><br/>
            <p className="mb-0">5.12 to provide you with notices about your account and/or subscription, including
              expiration and renewal notices, email-instructions, etc.; </p><br/>
            <p className="mb-0">5.13 to provide you with news, special offers and general information about other goods,
              services and events which we offer that are similar to those that you have already
              purchased or enquired about unless you have opted not to receive such information; </p><br/>
            <p className="mb-0">5.14 in any other way we may describe when you provide the information;</p><br/>
            <p className="mb-0">5.15 for any other purpose with your consent. </p><br/>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              6. Retention of Data
            </h4>
            <p className="mb-0">We will retain your Personal Data only for as long as is necessary for the purposes set
              out in
              this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply
              with our legal obligations (for example, if we are required to retain your data to comply with
              applicable laws), resolve disputes, and enforce our legal agreements and policies. </p><br/>
            <p className="mb-0">We will also retain Usage Data for internal analysis purposes. Usage Data is generally
              retained
              for a shorter period, except when this data is used to strengthen the security or to improve the
              functionality of our Service, or we are legally obligated to retain this data for longer time
              periods. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              7.Transfer of Data
            </h4>
            <p className="mb-0">Your information, including Personal Data, may be transferred to – and maintained on –
              computers located outside of your state, province, country or other governmental jurisdiction
              where the data protection laws may differ from those of your jurisdiction. </p><br/>
            <p className="mb-0">If you are located outside Sri Lanka and choose to provide information to us, please
              note that
              we transfer the data, including Personal Data, to Sri Lanka and process it there. </p><br/>
            <p className="mb-0">Your consent to this Privacy Policy followed by your submission of such information
              represents
              your agreement to that transfer. </p><br/>
            <p className="mb-0">SL Flicks will take all the steps reasonably necessary to ensure that your data is
              treated
              securely and in accordance with this Privacy Policy and no transfer of your Personal Data will
              take place to an organization or a country unless there are adequate controls in place including
              the security of your data and other personal information. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              8.Disclosure of Data
            </h4>
            <p className="mb-0">We may disclose personal information that we collect, or you provide: </p><br/>
            <h6>8.1. Disclosure for Law Enforcement. </h6>
            <p className="mb-0">Under certain circumstances, we may be required to disclose your Personal Data if
              required to
              do so by law or in response to valid requests by public authorities. </p><br/>
            <h6>8.2. Business Transaction. </h6>
            <p className="mb-0">If we or our subsidiaries are involved in a merger, acquisition or asset sale, your
              Personal Data
              may be transferred.</p><br/>
            <h6>8.3. Other cases. We may disclose your information also: </h6>
            <p className="mb-0">8.3.1. to our subsidiaries and affiliates; </p>
            <p className="mb-0">8.3.2. to contractors, service providers, and other third parties we use to support
              our business; </p>
            <p className="mb-0">8.3.3. to fulfill the purpose for which you provide it; </p>
            <p className="mb-0">8.3.4. for the purpose of including your company’s logo on our website; </p>
            <p className="mb-0">8.3.5. for any other purpose disclosed by us when you provide the information; </p>
            <p className="mb-0">8.3.6. with your consent in any other cases; </p>
            <p className="mb-0">8.3.7. if we believe disclosure is necessary or appropriate to protect the rights,
              property, or safety of the Company, our customers, or others. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              9. Security of Data
            </h4>
            <p className="mb-0">The security of your data is important to us but remember that no method of transmission
              over
              the Internet or method of electronic storage is 100% secure. While we strive to use
              commercially acceptable means to protect your Personal Data, we cannot guarantee its </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)
            </h4>
            <p className="mb-0">If you are a resident of the European Union (EU) and European Economic Area (EEA), you
              have
              certain data protection rights, covered by GDPR.</p><br/>
            <p className="mb-0">We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use
              of your
              Personal Data. </p><br/>
            <p className="mb-0">If you wish to be informed what Personal Data we hold about you and if you want it to be
              removed from our systems, please email us at info@slflicks.com. </p><br/>
            <p className="mb-0"></p>In certain circumstances, you have the following data protection rights: <br/>
            <p className="mb-0">10.1. Right to access: You have the right to access your personal information that we
              hold about you </p>
            <p className="mb-0">10.2. the right of rectification. You have the right to have your information rectified
              if that
              information is inaccurate or incomplete; </p>
            <p className="mb-0">10.3. the right to object. You have the right to object to our processing of your
              Personal
              Data; </p>
            <p className="mb-0">10.4. the right of restriction. You have the right to request that we restrict the
              processing
              of your personal information;</p>
            <p className="mb-0">10.5. the right to data portability. You have the right to be provided with a copy of
              your
              Personal Data in a structured, machine-readable and commonly used format; </p>
            <p className="mb-0">10.6. the right to withdraw consent. You also have the right to withdraw your consent at
              any time where we rely on your consent to process your personal information; </p><br/>
            <p className="mb-0">Please note that we may ask you to verify your identity before responding to such
              requests.
              Please note, we may not able to provide Service without some necessary data. </p>
            <p className="mb-0">You have the right to complain to a Data Protection Authority about our collection and
              use of
              your Personal Data. For more information, please contact your local data protection authority in
              the European Economic Area (EEA).</p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)
            </h4>
            <p className="mb-0">CalOPPA is the first state law in the nation to require commercial websites and online
              services
              to post a privacy policy. The law’s reach stretches well beyond California to require a person or
              company in the United States (and conceivable the world) that operates websites collecting
              personally identifiable information from California consumers to post a conspicuous privacy
              policy on its website stating exactly the information being collected and those individuals with
              whom it is being shared, and to comply with this policy. </p><br/>
            <p> 11.01. users can visit our site anonymously; </p>
            <p> 11.02 our Privacy Policy link includes the word “Privacy”, and can easily be found on the home
              page of our website; </p>
            <p>11.03. users will be notified of any privacy policy changes on our Privacy Policy Page;</p>
            <p> 11.4. users are able to change their personal information by emailing us at info@slflicks.com </p><br/>
            <p> Our Policy on “Do Not Track” Signals: </p><br/>
            <p>We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do
              Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web
              browser to inform websites that you do not want to be tracked.</p><br/>
            <p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web
              browser. </p><br/>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)
            </h4>
            <p className="mb-0">If you are a California resident, you are entitled to learn what data we collect about
              you, ask to
              delete your data and not to sell (share) it. To exercise your data protection rights, you can make
              certain requests and ask us: </p><br/>
            <p>12.1. What personal information we have about you. If you make this request, we
              will return to you: </p><br/>
            <p className="mb-0">12.01.01. The categories of personal information we have collected about you. </p>
            <p className="mb-0">12.01.02. The categories of sources from which we collect your personal
              information. </p>
            <p className="mb-0">12.01.03. The business or commercial purpose for collecting or selling your personal
              information. </p>
            <p className="mb-0">12.01.04. The categories of third parties with whom we share personal information. </p>
            <p className="mb-0">12.01.05 The specific pieces of personal information we have collected about you. </p>
            <p className="mb-0">12.01.06. A list of categories of personal information that we have sold, along with the
              category
              of any other company we sold it to. If we have not sold your personal information, we will inform
              you of that fact. </p>
            <p className="mb-0">12.01.07 A list of categories of personal information that we have disclosed for a
              business
              purpose, along with the category of any other company we shared it with. </p><br/>
            <p>Please note, you are entitled to ask us to provide you with this information up to two times in a
              rolling twelve-month period. When you make this request, the information provided may be
              limited to the personal information we collected about you in the previous 12 months. </p><br/>
            <p>12.2. To delete your personal information. If you make this request, we will delete
              the personal information we hold about you as of the date of your request
              from our records and direct any service providers to do the same. In some
              cases, deletion may be accomplished through de-identification of the
              information. If you choose to delete your personal information, you may not
              be able to use certain functions that require your personal information to
              operate. </p><br/>
            <p>12.3. To stop selling your personal information. We don’t sell or rent your personal
              information to any third parties for any purpose. We do not sell your
              personal information for monetary consideration. However, under some
              circumstances, a transfer of personal information to a third party, or within
              our family of companies, without monetary consideration may be considered
              a “sale” under California law. You are the only owner of your Personal Data
              and can request disclosure or deletion at any time. </p><br/>
            <p>If you submit a request to stop selling your personal information, we will stop making such
              transfers.</p><br/>
            <p>Please note, if you ask us to delete or stop selling your data, it may impact your experience with
              us, and you may not be able to participate in certain programs or membership services which
              require the usage of your personal information to function. But in no circumstances, we will
              discriminate against you for exercising your rights. </p><br/>
            <p>To exercise your California data protection rights described above, please send your request(s)
              by email: info@slflicks.com </p><br/>
            <p>Your data protection rights, described above, are covered by the CCPA, short for the California
              Consumer Privacy Act. To find out more, visit the official California Legislative Information
              website. The CCPA took effect on 01/01/2020. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              13. Service Providers
            </h4>
            <p className="mb-0">We may employ third party companies and individuals to facilitate our Service (“Service
              Providers”), provide Service on our behalf, perform Service-related services or assist us in
              analysing how our Service is used.</p><br/>
            <p>These third parties have access to your Personal Data only to perform these tasks on our behalf
              and are obligated not to disclose or use it for any other purpose. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              14. Analytics
            </h4>
            <p className="mb-0">We may use third-party Service Providers to monitor and analyze the use of our
              Service. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              15. CI/CD tools
            </h4>
            <p className="mb-0">We may use third-party Service Providers to automate the development process of our
              Service.</p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              16. Advertising
            </h4>
            <p className="mb-0">We may use third-party Service Providers to show advertisements to you to help support
              and
              maintain our Service.</p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              17. Behavioral Remarketing
            </h4>
            <p className="mb-0">We may use remarketing services to advertise on third party websites to you after you
              visited
              our Service. We and our third-party vendors use cookies to inform, optimise and serve ads
              based on your past visits to our Service. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">
              18. Payments
            </h4>
            <p className="mb-0">We may provide paid products and/or services within Service. In that case, we use
              third-party
              services for payment processing (e.g. payment processors). </p><br/>
            <p className="mb-0">We will not store or collect your payment card details. That information is provided
              directly to our
              third-party payment processors whose use of your personal information is governed by their
              Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as
              managed by the PCI Security Standards Council, which is a joint effort of brands like Visa,
              Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure
              handling of payment information. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">19. Links to Other Sites
            </h4>
            <p className="mb-0">Our Service may contain links to other sites that are not operated by us. If you click a
              third party
              link, you will be directed to that third party’s site. We strongly advise you to review the Privacy
              Policy of every site you visit. </p><br/>
            <p className="mb-0">We have no control over and assume no responsibility for the content, privacy policies
              or
              practices of any third party sites or services. </p><br/>
            <p className="mb-0">For example, the outlined privacy policy has been made using PolicyMaker.io, a free tool
              that
              helps create high-quality legal documents. PolicyMaker’s privacy policy generator is an easy
              touse tool for creating a privacy policy for blog, website, e-commerce store or mobile app. </p><br/>
          </div>
          <div className="title-box">
            <h4 className="mb-4">20. Children’s Privacy
            </h4>
            <p className="mb-0">Our Services are not intended for use by children under the age of 18 (“Child” or
              “Children”).</p><br/>
            <p className="mb-0">We do not knowingly collect personally identifiable information from Children under 18.
              If you
              become aware that a Child has provided us with Personal Data, please contact us. If we
              become aware that we have collected Personal Data from Children without verification of
              parental consent, we take steps to remove that information from our servers.</p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">21. Changes to This Privacy Policy
            </h4>
            <p className="mb-0">We may update our Privacy Policy from time to time. We will notify you of any changes by
              posting the new Privacy Policy on this page.  </p><br/>
            <p className="mb-0">We will let you know via email and/or a prominent notice on our Service, prior to the change
              becoming effective and update “effective date” at the top of this Privacy Policy. </p><br/>
            <p className="mb-0">You are advised to review this Privacy Policy periodically for any changes. Changes to this
              Privacy Policy are effective when they are posted on this page. </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">22. Contact Us
            </h4>
            <p className="mb-0">If you have any questions about this Privacy Policy, please contact us by email:
              info@slflicks.com  </p>
          </div>
          <div className="title-box">
            <h4 className="mb-4">Refund policy
            </h4>
            <p className="mb-0">Thank you for using our “SL Flicks” Sri Lankan OTT platform to stream content globally.
              We strive to ensure your experience is smooth and enjoyable. However, we understand
              that there may be situations where you need to request a refund. This Refund Policy
              outlines the guidelines and procedures for requesting refunds for our streaming
              services.  </p><br/>
            <p className="mb-0">1.Eligibility for Refund: Subscription Fees: You may be eligible for a refund of
              subscription fees under the following circumstances: - If you accidentally subscribed to
              our service and request a refund within 24 hours of subscribing. - If our service
              experiences prolonged downtime or technical issues that prevent you from accessing
              the content for an extended period, and we cannot fix the problem within a reasonable
              time. - If there are significant disruptions or interruptions caused by our platform's fault,
              and we cannot restore the service within a reasonable time. </p><br/>
            <p className="mb-0">2.Requesting a Refund: Subscription Fees: To request a refund for subscription fees,
              please contact our customer support team within 24 hours of subscribing. You can
              reach us through the designated channels specified on our website. Provide your
              account information and explain the reason for your refund request.  </p><br/>
            <p className="mb-0">3.Refund Processing: Subscription Fees: If your refund request for subscription fees
              meets the eligibility criteria mentioned above, we will process the refund within a
              reasonable time. The refunded amount will be credited back to the original payment
              method used for the subscription.  </p><br/>
            <p className="mb-0">4.Non-Refundable Items: Subscriptions: Once the subscription period has started, we
              do not provide partial refunds for the remaining unused period. 4.2 Convenience Fees:
              Any convenience fees or charges associated with payment processing are
              nonrefundable.  </p><br/>
            <p className="mb-0">5.Modification or Termination: We reserve the right to modify, update, or terminate this
              Refund Policy at any time, with or without prior notice. Any changes will be effective
              immediately upon posting the updated policy on our website.  </p><br/>
            <p className="mb-0">*Please note that this Refund Policy applies specifically to our “SL Flicks” Sri Lankan
              OTT platform for streaming content globally. If you have any further questions or need
              assistance regarding refunds, please contact our customer support team using the
              channels provided on our website.  </p><br/>
            <p className="mb-0">Last updated: March 5, 2024 </p><br/>
          </div>
        </Container>
      </div>
    </Fragment>
  );
});

PrivacyPolicy.displayName = "PrivacyPolicy";
export default PrivacyPolicy;
